### PR TITLE
New design for view/controller interaction and music functionality with  play() and stop() functions  <feature

### PR DESCRIPTION
**Pull request by xcwfwf44**
Please check this work and see if you understand this design. This design facilitates lose coupling between the GUI and Controller and makes it easy to see the general functionality and connectivity between classes by looking at the Controller. I propose that interaction between classes be done the way it has now been implemented for the MP3 and GUI class.  <feature

### CODE REVIEW

**Comment by tadzjibov** [comment]
looks good <feature, review

**Comment by humanjas** [comment]
New design looks good <feature, review

**Comment by RaviShivam** [comment]
I agree to the new design and also checked the functionality. The only thing that was missing was the action done by the exit button to terminate the audio which I updated. Good work <bug

**Comment by RaviShivam** [comment]
However, in your future commits. Could you discard the application.log and database.json file. It can be done with 2 easy git commands. < bug

**Pull request merged**
