### PR TITLE
Extract Class refactoring <organisation

### PR DESCRIPTION
**Pull request by tadzjibov**
Moved a part of controller to new class ConnectUnits <organisation

### CODE REVIEW

**Comment by RaviShivam** [comment]
great work! <organization

**Comment by RaviShivam** [comment]
your branch is conflicting with the master, Can you take a look into this? < bug

**Comment by humanjas** [comment]
Looks really good, only thing is the already mentioned merge conflict <bug

**Comment by Rightful** [comment]
Fine <organisation

**Comment by tadzjibov** [comment]
thnx for merge conflict fix <bug

**Pull request merged**
