### PR TITLE
added a test for the controller <testing

### PR DESCRIPTION
**Pull request by xcwfwf44**

### CODE REVIEW

**Comment by humanjas** [comment]
Could you remove the application.log file and check if you can do something with the travis erros? < bug

**Comment by RaviShivam** [comment]
Your tests are still failing. Can you take a look at this? < testing < bug

**Comment by xcwfwf44** [comment]
application.log really has to go into the gitignore.. this is just stupid <organisation

**Comment by RaviShivam** [comment]
Are these the only test that you have for controller? Because there is a lot more going on in the controller package. < testing

**Pull request merged**
