### PR TITLE
Problems fixed about 290 and 8 left. <organisation, bug.

### PR DESCRIPTION
**Pull request by Rightful**
Done with checkstyle etc.

### CODE REVIEW

**Comment by RaviShivam** [comment]
your checks are failing < bug

**Comment by Rightful** [comment]
Build fixed, please review and accept.

**Comment by RaviShivam** [comment]
good job fixing build. <bug

**Comment by humanjas** [comment]
Looks good, hope we can fix the last 8 errors as well before we merge.

**Pull request closed without merging**
