### PR TITLE
Kasper controlller refactoring, pom plugin fixes <organisation

### PR DESCRIPTION
**Pull request by xcwfwf44**

### CODE REVIEW

**Comment by Rightful** [comment]
Look at your execution, because the build is failing <bug

**Comment by xcwfwf44** [comment]
yes after adding executions as described here http://octopull.rmhartog.me/ .. it considers the pom to be malformed.. some other fix is needed.. but rather keep this for the next build

**Comment by Rightful** [comment]
please dont push your application.log or database.json, when you play the game, it will be logged in there so just discard those changes tnx, if you do this the rest looks fine <organization

**Comment by xcwfwf44** [comment]
these type of files should be in .gitignore.. so please do not remove them from there

**Comment by humanjas** [comment]
Looks good <organisaton

**Pull request merged**
