### PR TITLE
Added new tests for model and Controller package <test

### PR DESCRIPTION
**Pull request by RaviShivam**

### CODE REVIEW

**Comment by RaviShivam** [comment]
Please do not review yet. I will fix the travis build and recommit my changes < orginisation

**Comment by RaviShivam** [comment]
The test are all passing. can you check the if you agree and merge? < test

**Comment by humanjas** [comment]
The test for powerup had already been done in juggernaut, I tested all the inherited methods in Juggernauttest too, but it isn't bad to test it again. Could you remove your database.json file?
Other than that, good job.

**Comment by humanjas** [comment]
< test

**Pull request closed without merging**
